import { spielstand, speichereSpielstand } from './state.js';
import { fetchWithProxy } from './utils.js';

/**
 * Helper to apply "auto-going" status to all roster players who haven't responded yet.
 * @param {Object} event The calendar event to update
 */
export function applyAutoGoing(event) {
    if (!event.responses) event.responses = {};
    const roster = spielstand.roster || [];
    const assignments = spielstand.rosterAssignments || {};
    
    roster.forEach(p => {
        const name = p.name || `Spieler #${p.number}`;
        const assignedUid = Object.keys(assignments).find(u => assignments[u] === name);
        const key = assignedUid || `manual_${name.replace(/\s+/g, '_')}`;
        
        // Only set status if they haven't voted or if current status is auto-generated
        if (!event.responses[key] || event.responses[key].isAutoGenerated) {
            event.responses[key] = { 
                status: 'going', 
                name, 
                updatedAt: Date.now(), 
                isAutoGenerated: true 
            };
        }
    });
}

// =============================================================================
// TEAM URL PARSING
// =============================================================================

/**
 * Extracts the unique team ID from a handball.net team page URL.
 * Supports URLs like:
 *   https://www.handball.net/mannschaften/handball4all.westfalen.1289886/
 *   https://www.handball.net/mannschaften/handball4all.westfalen.1289886/spielplan
 * @param {string} url
 * @returns {string|null} The team ID (e.g. "handball4all.westfalen.1289886") or null
 */
export function parseTeamUrl(url) {
    try {
        const match = url.match(/mannschaften\/(handball4all\.[^/]+)/i);
        if (match && match[1]) return match[1];
        return null;
    } catch (e) {
        return null;
    }
}

/**
 * Fetches team summary + table (which includes the tournament ID) from handball.net API.
 * @param {string} teamId  e.g. "handball4all.westfalen.1289886"
 * @returns {Promise<Object>} The full response including teamSummary and table info
 */
export async function fetchTeamTable(teamId) {
    const url = `https://www.handball.net/a/sportdata/1/widgets/team/${teamId}/table`;
    return await fetchWithProxy(url, { json: true });
}

/**
 * Fetches the full season schedule for a given tournament ID from handball.net API.
 * @param {string} tournamentId  e.g. "handball4all.westfalen.k10_m-kl_wfia"
 * @returns {Promise<Array>} Array of GameSummary objects
 */
export async function fetchTournamentSchedule(tournamentId) {
    const url = `https://www.handball.net/a/sportdata/1/widgets/tournament/${tournamentId}/schedule`;
    const data = await fetchWithProxy(url, { json: true });
    if (!data || !data.schedule || !data.schedule.data) {
        throw new Error('Ungültiges Spielplan-Format von handball.net');
    }
    return data.schedule.data;
}

/**
 * Syncs all games from handball.net that involve the user's team into the calendar.
 * - Filters only games where the configured team is home or away
 * - Creates calendar events with type "game", title, date, time, and location
 * - Skips games that are already in the calendar (duplicate detection via hnetGameId)
 *
 * @param {string} teamId  e.g. "handball4all.westfalen.1289886"
 * @returns {Promise<{added: number, skipped: number, tournamentName: string}>}
 */
export async function syncScheduleToCalendar(teamId, rules = {}) {
    // Step 1: Get team info & tournament ID
    const tableData = await fetchTeamTable(teamId);
    if (!tableData || !tableData.table || !tableData.table.tournament) {
        throw new Error('Konnte Turnier-ID nicht ermitteln. Bitte überprüfe den Team-Link.');
    }
    const tournamentId = tableData.table.tournament.id;
    const tournamentName = tableData.table.tournament.name || 'Liga';

    // Store tournament ID for dashboard table
    spielstand.settings.handballNetTournamentId = tournamentId;
    spielstand.settings.handballNetTeamId = teamId;

    // Step 2: Fetch full schedule
    const allGames = await fetchTournamentSchedule(tournamentId);

    // Step 3: Filter only this team's games
    const myGames = allGames.filter(g =>
        g.homeTeam?.id === teamId || g.awayTeam?.id === teamId
    );

    if (myGames.length === 0) {
        throw new Error(`Keine Spiele für dieses Team in der Ligatabelle gefunden.`);
    }

    // Step 4: Prepare calendar & sync
    if (!spielstand.calendarEvents) spielstand.calendarEvents = [];

    // Build DUAL duplicate index:
    // 1. By hnetGameId (for previously synced games)
    // 2. By date (YYYY-MM-DD) for manually entered games — prevents double entries
    const existingHnetIds = new Set(
        spielstand.calendarEvents
            .filter(e => e.hnetGameId)
            .map(e => e.hnetGameId)
    );
    const existingGameDates = new Set(
        spielstand.calendarEvents
            .filter(e => e.type === 'game' || e.type === 'spiel')
            .map(e => e.date?.slice(0, 10))
            .filter(Boolean)
    );

    let added = 0;
    let skipped = 0;
    let merged = 0;

    for (const game of myGames) {
        const hnetId = game.id;
        const isHome = game.homeTeam?.id === teamId;
        const opponent = isHome ? game.awayTeam?.name : game.homeTeam?.name;
        const startMs = game.startsAt;
        const startDate = new Date(startMs);
        const dateStr = startDate.toISOString().slice(0, 10); // YYYY-MM-DD
        const timeStr = startDate.toLocaleTimeString('de-DE', { hour: '2-digit', minute: '2-digit' });

        const eventRules = {
            requireReason: rules.requireReason || false,
            deadlineHours: rules.deadlineHours || 0,
            defaultStatus: rules.autoGoing ? 'going' : 'none'
        };

        // Check 1: Already synced via hnetGameId
        if (existingHnetIds.has(hnetId)) {
            const existingEvent = spielstand.calendarEvents.find(e => e.hnetGameId === hnetId);
            if (existingEvent) {
                // Update rules even for existing games
                existingEvent.rules = eventRules;
                // If autoGoing is requested, apply it to those who haven't responded yet
                if (rules.autoGoing) {
                    applyAutoGoing(existingEvent);
                }
            }
            skipped++;
            continue;
        }

        // Check 2: A game entry already exists on this date (manual entry) → tag it instead of duplicating
        if (existingGameDates.has(dateStr)) {
            // Find the existing event and tag it with the hnetGameId so future syncs skip it
            const existingEvent = spielstand.calendarEvents.find(e =>
                (e.type === 'game' || e.type === 'spiel') &&
                e.date?.slice(0, 10) === dateStr &&
                !e.hnetGameId
            );
            if (existingEvent) {
                existingEvent.hnetGameId = hnetId;
                existingEvent.rules = eventRules; // Apply rules to merged event too
                if (rules.autoGoing) {
                    applyAutoGoing(existingEvent);
                }
                existingHnetIds.add(hnetId);
                merged++;
                continue;
            }
        }

        const location = game.field?.name && game.field?.city
            ? `${game.field.name}, ${game.field.city}`
            : (game.field?.name || '');

        const title = isHome
            ? `${tableData.teamSummary?.name || 'Wir'} vs. ${opponent}`
            : `${opponent} vs. ${tableData.teamSummary?.name || 'Wir'} (A)`;

        const calendarEvent = {
            id: `hnet_${hnetId}_${Date.now()}`,
            hnetGameId: hnetId,
            title: title,
            date: dateStr,
            time: timeStr,
            type: 'game',
            location: location,
            isAuswaerts: !isHome,
            opponent: opponent,
            notes: game.state === 'Post' && game.homeGoals != null
                ? `Ergebnis: ${game.homeGoals}:${game.awayGoals}`
                : '',
            rules: eventRules,
            responses: {}, // Empty start
            createdAt: new Date().toISOString()
        };

        if (rules.autoGoing) {
            applyAutoGoing(calendarEvent);
        }

        spielstand.calendarEvents.push(calendarEvent);
        existingHnetIds.add(hnetId);
        existingGameDates.add(dateStr);
        added++;
    }

    speichereSpielstand();

    return { added, skipped, merged, total: myGames.length, tournamentName };
}



/**
 * Parses the game ID from a handball.net URL.
 * URL Example: https://www.handball.net/spiele/handball4all.westfalen.8348616/spielbericht
 */
export function parseGameId(url) {
    try {
        const parts = url.split('/');
        // The ID is usually the part before 'spielbericht' or 'spielplan'
        for (let i = 0; i < parts.length; i++) {
            if (parts[i] === 'spiele' && parts[i + 1]) {
                return parts[i + 1].split('?')[0];
            }
        }
        return null;
    } catch (e) {
        return null;
    }
}

/**
 * Fetches game data from handball.net API
 */
export async function fetchHandballNetGame(id) {
    const url = `https://www.handball.net/a/sportdata/1/games/${id}/combined`;
    return await fetchWithProxy(url, { json: true });
}

console.warn("[V4_SAFETY_NET] Handball.net Importer Active - Final Defense");

/**
 * Maps handball.net JSON to internal game object.
 * @param {Object} rawJson The JSON from /games/{id}/combined
 * @param {String} myTeamName The user's team name for perspective
 */
export function mapHandballNetToInternal(rawJson, myTeamName) {
    // Game reports from /combined are always wrapped in a "data" property
    const data = rawJson.data || rawJson;
    if (!data || !data.summary) {
        console.error("[Import] Unexpected JSON structure:", rawJson);
        throw new Error("Ungültiges Datenformat (summary fehlt).");
    }

    console.log("%c[DEBUG IMPORT] Starting Mapping...", "color: #3b82f6; font-weight: bold; font-size: 14px;");
    console.log("[DEBUG IMPORT] My Team (Settings):", myTeamName);

    const summary = data.summary;
    const homeTeam = summary.homeTeam || { name: "Heim" };
    const awayTeam = summary.awayTeam || { name: "Gast" };

    // Convert startsAt (Unix timestamp in ms) to ISO string for our app
    let gameDate = new Date().toISOString(); 
    if (summary.startsAt) {
        gameDate = new Date(summary.startsAt).toISOString();
    }

    // Detect perspective (is the user's team home or away?)
    // Improved detection: Check both teams and pick the one that matches better
    const homeName = (homeTeam.name || "").toLowerCase();
    const awayName = (awayTeam.name || "").toLowerCase();
    const searchName = (myTeamName || "").toLowerCase();

    let isAuswaerts = false;
    if (searchName) {
        // If our name is in the away name but not home name (or away name is a better match)
        const homeMatch = homeName.includes(searchName);
        const awayMatch = awayName.includes(searchName);
        
        if (awayMatch && !homeMatch) {
            isAuswaerts = true;
        } else if (homeMatch && awayMatch) {
            // Tie breaker: which one is more similar in length or exact?
            isAuswaerts = Math.abs(awayName.length - searchName.length) < Math.abs(homeName.length - searchName.length);
        } else if (!homeMatch && !awayMatch) {
            // Fallback: try very loose matching (words)
            const words = searchName.split(/\s+/).filter(w => w.length > 2);
            const homeWordMatch = words.some(w => homeName.includes(w));
            const awayWordMatch = words.some(w => awayName.includes(w));
            if (awayWordMatch && !homeWordMatch) isAuswaerts = true;
        }
    }
 
    console.log(`[DEBUG IMPORT] Teams: Home='${homeName}', Away='${awayName}'`);
    console.log(`[DEBUG IMPORT] DETECTED: isAuswaerts = ${isAuswaerts}`);
    
    // Handled wrapped data if present
    const lineup = data.lineup || {};
    const hnetHomePlayers = lineup.home || [];
    const hnetAwayPlayers = lineup.away || [];
    
    // Safety check: Compare score order vs team order
    // In Hnet API combined, summary.homeTeam is always the team that matches events with team: 'Home'
    const ourHnetPlayers = isAuswaerts ? hnetAwayPlayers : hnetHomePlayers;
    const theirHnetPlayers = isAuswaerts ? hnetHomePlayers : hnetAwayPlayers;

    // Helper to map players
    const mapPlayers = (hnetList) => hnetList.map(p => {
        const fn = p.player?.firstname || p.firstname || "";
        const ln = p.player?.lastname || p.lastname || "";
        let fullName = (fn + " " + ln).trim();
        
        // Try to find the number in various common fields
        const jerseyNum = p.player?.jerseyNumber || p.jerseyNumber || p.number || "";
        
        if (fullName === "N.N. N.N." || !fullName) fullName = `Spieler #${jerseyNum || '?'}`;
        
        return {
            name: fullName,
            number: String(jerseyNum),
            isGoalkeeper: !!(p.position?.toLowerCase().includes('torwart') || p.position?.toLowerCase().includes('gk'))
        };
    });

    const roster = mapPlayers(ourHnetPlayers);
    const knownOpponents = mapPlayers(theirHnetPlayers);

    // Map Events to GameLog
    let splitIndex = -1;
    let maxTimeSeen = -1;
    
    // SORT events by TIMESTAMP ascending to ensure perfect chronological order
    // This is the most robust way regardless of ID or provided order.
    const events = (data.events || []).sort((a, b) => (a.timestamp || 0) - (b.timestamp || 0));

    // PASS 1: Find the halftime split point (Time jump or StopPeriod marker around 30m)
    for (let i = 0; i < events.length; i++) {
        const e = events[i];
        if (!e.time) continue; // IGNORE events without time for split detection!
        
        const timeSecs = (parseInt(e.time.split(':')[0]) * 60 + parseInt(e.time.split(':')[1]));
        
        // Signal 1: Marker from API (StopPeriod)
        if (e.type === 'StopPeriod' && timeSecs > 1500 && timeSecs < 3300) {
            splitIndex = i;
            break;
        }
        // Signal 2: Physical time jump (e.g. 30:05 -> 00:00)
        // Must be a jump to a valid low time, not just missing data
        if (maxTimeSeen > 1600 && timeSecs < maxTimeSeen - 600 && timeSecs < 600) {
            splitIndex = i;
            break;
        }
        maxTimeSeen = Math.max(maxTimeSeen, timeSecs);
    }

    // PASS 2: Map and Tag
    const gameLog = [];

    events.forEach((e, idx) => {
        const type = e.type;
        const timeSecs = e.time ? (parseInt(e.time.split(':')[0]) * 60 + parseInt(e.time.split(':')[1])) : 0;
        const isActionByOurTeam = (isAuswaerts && e.team === 'Away') || (!isAuswaerts && e.team === 'Home');
        
        if (idx < 5) {
            console.log(`[DEBUG IMPORT] Event #${idx}: Team=${e.team}, Action=${type}, ByUs=${isActionByOurTeam}`);
        }
        
        // EVERYTHING on or before splitIndex belongs to H1.
        // EVERYTHING after splitIndex belongs to H2.
        const currentHalf = (splitIndex !== -1 && idx > splitIndex) ? 2 : 1;

        // Map Period markers
        if (type === 'StopPeriod' || (e.message && e.message.toLowerCase().includes('halbzeit'))) {
            const isHalftime = (timeSecs < 2400); // < 40 mins
            gameLog.push({
                time: e.time || (isHalftime ? '30:00' : '60:00'),
                action: isHalftime ? 'Halbzeit' : 'Spielende',
                half: isHalftime ? 1 : 2, 
                manualShift: 0,
                timestamp: e.timestamp || null,
                spielstand: e.score || "",
                importMeta: { hnetId: `${isHalftime ? 'half' : 'end'}_${idx}` }
            });
            return;
        }

        let action = null;
        const typeLower = (type || "").toLowerCase();
        
        // Map common goal types
        if (typeLower.includes('goal') || typeLower.includes('tor')) {
            action = isActionByOurTeam ? 'Tor' : 'Gegner Tor';
            if (typeLower.includes('seven')) action = isActionByOurTeam ? '7m Tor' : 'Gegner 7m Tor';
        } 
        else if (type === 'TwoMinutePenalty' || typeLower.includes('minute')) action = isActionByOurTeam ? '2 Minuten' : 'Gegner 2 Minuten';
        else if (type === 'YellowCard' || typeLower.includes('yellow')) action = isActionByOurTeam ? 'Gelbe Karte' : 'Gegner Gelbe Karte';
        else if (type === 'RedCard' || typeLower.includes('red')) action = isActionByOurTeam ? 'Rote Karte' : 'Gegner Rote Karte';
        else if (type === 'BlueCard' || typeLower.includes('blue')) action = isActionByOurTeam ? 'Blaue Karte' : 'Gegner Blaue Karte';
        else if (type === 'TeamTimeout' || type === 'Timeout') action = isActionByOurTeam ? 'Timeout' : 'Gegner Timeout';
        
        // FALLBACK: If score changed but no goal action identified yet
        if (!action && e.score) {
            const currentScoreParts = e.score.split(':').map(n => parseInt(n.trim()));
            // We'd need the previous score to be 100% sure, but usually we can check if it's a known goal type from the message
            const msg = (e.message || "").toLowerCase();
            if (msg.includes("tor") || msg.includes("treffer") || msg.includes("erzielt")) {
                action = isActionByOurTeam ? 'Tor' : 'Gegner Tor';
                if (msg.includes("7m") || msg.includes("siebenmeter")) action = isActionByOurTeam ? '7m Tor' : 'Gegner 7m Tor';
            }
        }
        
        if (!action) return;

        let jerseyNumber = e.player?.jerseyNumber || "";
        if (!jerseyNumber && e.message) {
            const msg = e.message;
            // 1. Classic: "Tor durch Name (Num.)"
            const matchParentheses = msg.match(/\((\d+)\.?\)/);
            if (matchParentheses) {
                jerseyNumber = matchParentheses[1];
            } else {
                // 2. N.N. Case: "Tor durch 29. (Letmather TV 2)"
                const matchNaked = msg.match(/durch (\d+)\. \(/i);
                if (matchNaked) jerseyNumber = matchNaked[1];
            }
        }

        let playerName = "";
        let finalPlayerId = null;
        let finalGegnerId = null;

        if (jerseyNumber) {
            finalPlayerId = isActionByOurTeam ? String(jerseyNumber) : null;
            finalGegnerId = !isActionByOurTeam ? String(jerseyNumber) : null;

            // Find player name from the correct list
            const searchList = isActionByOurTeam ? roster : knownOpponents;
            const found = searchList.find(p => String(p.number) === String(jerseyNumber));
            if (found) {
                playerName = found.name;
            } else {
                playerName = (isActionByOurTeam ? "Spieler #" : "Gegner #") + jerseyNumber;
            }
        } else {
            // Team Goal / No player info
            if (isActionByOurTeam) {
                finalPlayerId = "TEAM_US";
                playerName = "Mannschaft (Wir)";
            } else {
                finalGegnerId = "TEAM_OPP";
                playerName = "Mannschaft (Gegner)";
            }
        }

        gameLog.push({
            time: e.time || '00:00',
            action: action,
            half: currentHalf,
            manualShift: 0,
            timestamp: e.timestamp || null,
            playerName: playerName,
            playerId: finalPlayerId,
            gegnerNummer: finalGegnerId,
            spielstand: e.score || "0:0",
            importMeta: { hnetId: e.id || `event_${idx}` }
        });
    });

    // --- AUTO-POPULATE ROSTERS FROM LOG (Safety Net) ---
    // If the API lineup was incomplete, we rebuild it from the actual game events
    gameLog.forEach(e => {
        const isUs = !e.action.toLowerCase().includes('gegner');
        const num = e.playerId || e.gegnerNummer;
        if (!num) return;

        const targetList = isUs ? roster : knownOpponents;
        const exists = targetList.some(p => String(p.number) === String(num));
        
        if (!exists) {
            targetList.push({
                name: e.playerName || (isUs ? `Spieler #${num}` : `Gegner #${num}`),
                number: String(num),
                isGoalkeeper: false
            });
        }
    });

    // Final sanity check: Add Spielende if missing
    if (!gameLog.some(e => e.action === 'Spielende')) {
        const lastEvent = gameLog[gameLog.length - 1];
        gameLog.push({
            time: (lastEvent && parseTime(lastEvent.time) > 2000) ? lastEvent.time : '60:00',
            action: 'Spielende',
            half: 2,
            importMeta: { hnetId: 'sanity_end' }
        });
    }

    // Ultra-defensive score lookup (Check all known variants)
    const heimTore = Number(summary.homeGoals ?? summary.scoreHome ?? 0);
    const gegnerTore = Number(summary.awayGoals ?? summary.scoreAway ?? 0);

    // Final Object
    const result = {
        date: gameDate,
        isImportedOnly: true,
        score: {
            heim: isNaN(heimTore) ? 0 : heimTore,
            gegner: isNaN(gegnerTore) ? 0 : gegnerTore
        },
        teams: {
            heim: homeTeam.name || "Heimteam",
            gegner: awayTeam.name || "Gastteam"
        },
        gameLog: gameLog,
        roster: roster,
        knownOpponents: knownOpponents,
        settings: {
            teamNameHeim: homeTeam.name || "Heimteam",
            teamNameGegner: awayTeam.name || "Gastteam",
            myTeamName: myTeamName || (isAuswaerts ? awayTeam.name : homeTeam.name),
            isAuswaertsspiel: isAuswaerts
        },
        hnetGameId: summary.id || null,
        importDate: new Date().toISOString()
    };
    
    console.log(`[Import] Finished mapping. Perspective: ${isAuswaerts ? 'Away' : 'Home'}, MyTeam: ${result.settings.myTeamName}`);
    return result;
}
