import { useState, useRef, useEffect, useCallback } from 'react';
import { 
  getDay,
} from 'date-fns';
import useStore from '../store/useStore';

export const useCalendarData = () => {
  const { 
    squad, 
    setCalendarEvents, 
    addAbsence: storeAddAbsence, 
    removeAbsence: storeRemoveAbsence,
    updateSubscriptions,
    updateSeries,
    updateEventStatus,
    activeMember,
    removeEvent
  } = useStore();

  const currentSquad = squad || { settings: {}, calendarEvents: [], absences: [], subscriptions: [], series: [], home: [], hiddenEventIds: [] };
  const { 
    calendarEvents: events = [], 
    absences = [], 
    subscriptions = [], 
    series = [], 
    settings = {}, 
    home: homeSquad = [],
    hiddenEventIds = []
  } = currentSquad;

  const [isSyncing, setIsSyncing] = useState(false);
  const isSyncingRef = useRef(false);

  const syncFromHnet = useCallback(async (offset = 60) => {
    // Helper to subtract minutes from "HH:mm"
    const getMeetingTime = (timeStr, min) => {
      try {
        const [h, m] = timeStr.replace(' Uhr', '').split(':').map(Number);
        const d = new Date();
        d.setHours(h, m, 0, 0);
        d.setMinutes(d.getMinutes() - min);
        return d.toLocaleTimeString('de-DE', { hour: '2-digit', minute: '2-digit' });
      } catch { return ''; }
    };

    // Read fresh data directly from the store at call time to avoid stale closures
    const freshState = useStore.getState();
    const freshSquad = freshState.squad || {};
    const freshSettings = freshSquad.settings || {};
    const freshHomeSquad = (Array.isArray(freshSquad.home) ? freshSquad.home : []).filter(p => !p.isInactive);
    const freshEvents = Array.isArray(freshSquad.calendarEvents) 
      ? freshSquad.calendarEvents 
      : Object.values(freshSquad.calendarEvents || {});
    const freshHiddenIds = freshSquad.hiddenEventIds || [];

    let teamId = freshSettings?.teamId;
    
    // Fallback: If teamId is missing or seems to be a Firebase ID, extract from URL
    if ((!teamId || teamId.length > 15) && freshSettings.hnetUrl) {
      const match = freshSettings.hnetUrl.match(/mannschaften\/([^/]+)/);
      if (match && match[1]) teamId = match[1];
    }

    if (!teamId || isSyncingRef.current) return;

    isSyncingRef.current = true;
    setIsSyncing(true);
    try {
      const { syncToCalendar } = await import('../services/handballNetService');
      const hnetEvents = await syncToCalendar(teamId, freshSettings.homeName || "Wir");
      
      const merged = [...freshEvents];
      
      hnetEvents.forEach(hEvent => {
        const hnetId = String(hEvent.hnetGameId || "");
        const idx = merged.findIndex(e => String(e.hnetGameId || "") === hnetId);
        const isHidden = freshHiddenIds.includes(hnetId);
        const isArchived = hEvent.status === 'archived';

        if (idx > -1) {
          // Existing event: update external data, preserve local settings, fill missing responses
          const existing = merged[idx];
          let responses = (existing.responses && !Array.isArray(existing.responses)) 
            ? { ...existing.responses } 
            : {};
          
          // Automatic responses
          freshHomeSquad.forEach(p => { 
            const playerName = p.name?.trim();
            if (!playerName || responses[playerName]) return;

            if (p.isInactive) {
              // Inactive players always decline by default
              responses[playerName] = { status: 'declined', reason: 'Spieler ist inaktiv', timestamp: new Date().toISOString(), isAutoGenerated: true };
            } else if (freshSettings.autoDabei && !isArchived) {
              // Active players accept if autoDabei is on
              responses[playerName] = { status: 'going', reason: '', timestamp: new Date().toISOString(), isAutoGenerated: true };
            }
          });
          merged[idx] = {
            ...existing,
            ...hEvent,
            date: hEvent.date + 'T' + hEvent.time.replace(' Uhr', ''),
            meetingTime: existing.meetingTime || getMeetingTime(hEvent.time, offset),
            responses,
            isMandatory: existing.isMandatory !== undefined ? existing.isMandatory : freshSettings.absageGrundPflicht,
            isAutoGoing: existing.isAutoGoing !== undefined ? existing.isAutoGoing : freshSettings.autoDabei,
            deadline: existing.deadline !== undefined ? existing.deadline : freshSettings.absageDeadline
          };
        } else if (!isHidden) {
          // New event
          const initialResponses = {};
          freshHomeSquad.forEach(p => { 
            const playerName = p.name?.trim();
            if (!playerName) return;

            if (p.isInactive) {
              initialResponses[playerName] = { status: 'declined', reason: 'Spieler ist inaktiv', timestamp: new Date().toISOString(), isAutoGenerated: true };
            } else if (freshSettings.autoDabei && !isArchived) {
              initialResponses[playerName] = { status: 'going', reason: '', timestamp: new Date().toISOString(), isAutoGenerated: true };
            }
          });
          merged.push({
            ...hEvent,
            date: hEvent.date + 'T' + hEvent.time.replace(' Uhr', ''),
            meetingTime: getMeetingTime(hEvent.time, offset),
            responses: initialResponses,
            isMandatory: freshSettings.absageGrundPflicht,
            isAutoGoing: freshSettings.autoDabei,
            deadline: freshSettings.absageDeadline
          });
        }
      });
      
      setCalendarEvents(merged);
      
      // PERSIST: Manually trigger a bulk save for external sync data
      const activeTeamId = useStore.getState().activeTeamId;
      if (activeTeamId) {
        const { default: syncService } = await import('../services/SyncService');
        syncService.saveBulkEvents(activeTeamId, merged);
      }
    } catch (e) {
      console.error("Hnet Sync Error:", e);
    } finally {
      isSyncingRef.current = false;
      setIsSyncing(false);
    }
  }, [setCalendarEvents]);

  // --- LAZY LOADING: Real-time Firestore Sync ---
  useEffect(() => {
    const activeTeamId = useStore.getState().activeTeamId;
    if (activeTeamId) {
      const subKey = `events_${activeTeamId}`;
      let isMounted = true;
      let sync;

      import('../services/SyncService').then(({ default: syncService }) => {
        if (!isMounted) return;
        sync = syncService;
        syncService.subscribeToEvents(activeTeamId, useStore.getState());
      });

      return () => {
        isMounted = false;
        if (sync) sync.unsubscribe(subKey);
      };
    }
  }, []);

  useEffect(() => {
    if (settings?.teamId && settings?.hnetUrl) {
      syncFromHnet();
    }
  }, [settings?.teamId, settings?.hnetUrl, syncFromHnet]);

  const handleUpdateStatus = (eventId, status, reason = '', playerName) => {
    const nameToUpdate = playerName || activeMember?.playerName;
    if (!nameToUpdate) return;
    updateEventStatus(eventId, nameToUpdate, status, reason);
  };

  const handleAddAbsence = (absenceData) => {
    const newAbs = { 
      type: absenceData.type, 
      reason: absenceData.reason, 
      ...(absenceData.type === 'Einmalig' ? { 
        start: absenceData.start, 
        end: absenceData.end 
      } : { 
        day: parseInt(absenceData.day) 
      }) 
    };
    storeAddAbsence(newAbs);
  };

  const executeDeletion = (type, id) => {
    if (type === 'event') removeEvent(id);
    else if (type === 'series') {
      const s = series.find(ser => ser.id === id);
      if (s) setCalendarEvents(events.filter(e => !(e.title === s.title && getDay(new Date(e.date)) === s.day && e.type === 'Training')));
      updateSeries(series.filter(ser => ser.id !== id));
    } else if (type === 'abo') {
      const sub = subscriptions.find(s => s.id === id);
      if (sub && sub.type === 'hnet') {
        // Remove all hnet events
        setCalendarEvents(events.filter(e => !e.hnetGameId && !e.id?.toString().startsWith('hnet_')));
      } else if (sub) {
        // Remove events from this specific subscription URL/ID
        setCalendarEvents(events.filter(e => e.subscriptionId !== id));
      }
      updateSubscriptions(subscriptions.filter(s => s.id !== id));
    } else if (type === 'absence') storeRemoveAbsence(id);
  };

  const saveSeriesTitle = (id, newTitle) => {
    const s = series.find(ser => ser.id === id);
    if (s && newTitle) {
      updateSeries(series.map(item => item.id === id ? { ...item, title: newTitle } : item));
      setCalendarEvents(events.map(e => (e.title === s.title && getDay(new Date(e.date)) === s.day) ? { ...e, title: newTitle } : e));
    }
  };

  return {
    events: (Array.isArray(events) ? events : Object.values(events || {})).map(e => ({ ...e, date: new Date(e.date) })), 
    setEvents: setCalendarEvents,
    absences: absences || [], 
    setAbsences: (a) => {}, // Managed via store actions now
    subscriptions: subscriptions || [], 
    setSubscriptions: updateSubscriptions,
    series: series || [], 
    setSeries: updateSeries,
    settings,
    homeSquad,
    isSyncing,
    syncFromHnet,
    handleUpdateStatus,
    handleAddAbsence,
    executeDeletion,
    saveSeriesTitle
  };
};
