import { useState } from 'react';
import { 
  format, 
  addWeeks,
  setHours,
  setMinutes,
  parse,
  getDay,
  addMonths
} from 'date-fns';
import { de } from 'date-fns/locale';

export const useEventEditor = (homeSquad, allMembers, setEvents, setSeries, setActiveModal) => {
  const [formError, setFormError] = useState(null);
  const [eventData, setEventData] = useState({ 
    id: null, 
    title: '', 
    type: 'Training', 
    date: format(new Date(), 'yyyy-MM-dd'), 
    time: '19:00', 
    meetingTime: '', 
    location: '', 
    repeat: 'Keine', 
    endDate: format(addMonths(new Date(), 3), 'yyyy-MM-dd'), 
    isMandatory: false, 
    isAutoGoing: false, 
    deadline: 0 
  });

  const handleSaveEvent = () => {
    setFormError(null);
    if (!eventData.title || !eventData.date) {
      setFormError("Bitte Titel und Datum ausfüllen.");
      return;
    }
    
    try {
      const datePart = parse(eventData.date, 'yyyy-MM-dd', new Date());
      const [h, m] = eventData.time.split(':');
      const baseDate = setMinutes(setHours(datePart, parseInt(h) || 0), parseInt(m) || 0);

      const initialResponses = {};
      homeSquad.forEach(player => {
        if (!player.name) return;

        const pName = player.name?.trim().toLowerCase();
        const isLinked = (allMembers || []).some(m => 
          (m.playerName?.trim().toLowerCase() === pName) || 
          (m.playerId === player.id)
        );
        if (!isLinked && !player.isInactive) return;

        if (player.isInactive) {
          initialResponses[player.name] = { 
            status: 'declined', 
            reason: 'Spieler ist inaktiv', 
            timestamp: new Date().toISOString(), 
            isAutoGenerated: true 
          };
        } else if (eventData.isAutoGoing) {
          initialResponses[player.name] = { 
            status: 'going', 
            reason: '', 
            timestamp: new Date().toISOString(), 
            isAutoGenerated: true 
          };
        }
      });

      if (eventData.id) {
        setEvents(prev => prev.map(e => e.id === eventData.id ? { 
          ...e, 
          title: eventData.title, 
          type: eventData.type, 
          date: format(datePart, 'yyyy-MM-dd'), 
          time: eventData.time, 
          meetingTime: eventData.meetingTime, 
          location: eventData.location, 
          isMandatory: eventData.isMandatory, 
          isAutoGoing: eventData.isAutoGoing, 
          deadline: eventData.deadline
        } : e));
      } else {
        if (eventData.repeat === 'Keine') {
          setEvents(prev => [...prev, { 
            id: Date.now(), 
            title: eventData.title, 
            type: eventData.type, 
            date: format(datePart, 'yyyy-MM-dd'), 
            time: eventData.time, 
            meetingTime: eventData.meetingTime, 
            location: eventData.location || 'Halle', 
            isMandatory: eventData.isMandatory, 
            isAutoGoing: eventData.isAutoGoing, 
            deadline: eventData.deadline, 
            responses: initialResponses 
          }]);
        } else {
          const stopDate = parse(eventData.endDate, 'yyyy-MM-dd', new Date());
          let current = baseDate;
          let newEvents = [];
          let i = 0;
          while (current <= stopDate && i < 100) {
            newEvents.push({ 
              id: Date.now() + i, 
              title: eventData.title, 
              type: eventData.type, 
              date: format(current, 'yyyy-MM-dd'), 
              time: eventData.time, 
              meetingTime: eventData.meetingTime, 
              location: eventData.location || 'Halle', 
              isMandatory: eventData.isMandatory, 
              isAutoGoing: eventData.isAutoGoing, 
              deadline: eventData.deadline, 
              responses: { ...initialResponses } 
            });
            current = addWeeks(current, eventData.repeat === 'Alle 2 Wochen' ? 2 : 1);
            i++;
          }
          setEvents(prev => [...prev, ...newEvents]);
          setSeries(prev => [...prev, { 
            id: Date.now(), 
            title: eventData.title, 
            rule: `${format(baseDate, 'eeee', { locale: de })}s – Serie bis ${format(stopDate, 'dd.MM.yy')}`, 
            day: getDay(baseDate) 
          }]);
        }
      }
      setActiveModal(null);
    } catch (err) {
      setFormError("Systemfehler: " + err.message);
    }
  };

  const resetEventData = (selectedDate) => {
    setEventData({ 
      id: null, 
      title: '', 
      type: 'Training', 
      date: format(selectedDate, 'yyyy-MM-dd'), 
      time: '19:00', 
      meetingTime: '', 
      location: '', 
      repeat: 'Keine', 
      endDate: format(addMonths(new Date(), 3), 'yyyy-MM-dd'),
      isMandatory: false, 
      isAutoGoing: false, 
      deadline: 0 
    });
  };

  return {
    eventData,
    setEventData,
    handleSaveEvent,
    formError,
    setFormError,
    resetEventData
  };
};
