import { format, addWeeks, getDay, parse, setHours, setMinutes } from 'date-fns';
import { de } from 'date-fns/locale';

/**
 * Generates initial responses for an event based on player status and auto-attendance settings.
 */
export const generateInitialResponses = (homeSquad, allMembers, isAutoGoing, isArchived) => {
  const initialResponses = {};
  homeSquad.forEach(player => {
    if (!player.name) return;

    const pName = player.name?.trim().toLowerCase();
    const isLinked = (allMembers || []).some(m => 
      (m.playerName?.trim().toLowerCase() === pName) || 
      (m.playerId === player.id)
    );
    if (!isLinked && !player.isInactive) return;

    if (player.isInactive) {
      initialResponses[player.name] = { 
        status: 'declined', 
        reason: 'Spieler ist inaktiv', 
        timestamp: new Date().toISOString(), 
        isAutoGenerated: true 
      };
    } else if (isAutoGoing && !isArchived) {
      initialResponses[player.name] = { 
        status: 'going', 
        reason: '', 
        timestamp: new Date().toISOString(), 
        isAutoGenerated: true 
      };
    }
  });
  return initialResponses;
};

/**
 * Generates a list of recurring events based on a start event and repeat rule.
 */
export const generateRecurringEvents = (eventData, initialResponses) => {
  const datePart = parse(eventData.date, 'yyyy-MM-dd', new Date());
  const [h, m] = eventData.time.split(':');
  const baseDate = setMinutes(setHours(datePart, parseInt(h) || 0), parseInt(m) || 0);
  const stopDate = parse(eventData.endDate, 'yyyy-MM-dd', new Date());
  
  let current = baseDate;
  let newEvents = [];
  let i = 0;
  
  while (current <= stopDate && i < 100) {
    newEvents.push({ 
      id: Date.now() + i, 
      title: eventData.title, 
      type: eventData.type, 
      date: format(current, 'yyyy-MM-dd'), 
      time: eventData.time, 
      meetingTime: eventData.meetingTime, 
      location: eventData.location || 'Halle', 
      isMandatory: eventData.isMandatory, 
      isAutoGoing: eventData.isAutoGoing, 
      deadline: eventData.deadline, 
      responses: { ...initialResponses } 
    });
    current = addWeeks(current, eventData.repeat === 'Alle 2 Wochen' ? 2 : 1);
    i++;
  }

  const seriesInfo = {
    id: Date.now(),
    title: eventData.title,
    rule: `${format(baseDate, 'eeee', { locale: de })}s – Serie bis ${format(stopDate, 'dd.MM.yy')}`,
    day: getDay(baseDate)
  };

  return { newEvents, seriesInfo };
};

/**
 * Formats a date string for the calendar.
 */
export const formatCalendarDate = (dateStr, timeStr) => {
  return dateStr + 'T' + timeStr.replace(' Uhr', '');
};
