/**
 * Helper to calculate meeting time based on match time and offset minutes
 */
export const calculateMeetingTime = (timeStr, offset) => {
  if (!timeStr || !offset) return '';
  try {
    const [h, m] = timeStr.replace(' Uhr', '').split(':').map(Number);
    const d = new Date();
    d.setHours(h, m, 0, 0);
    d.setMinutes(d.getMinutes() - offset);
    return d.toLocaleTimeString('de-DE', { hour: '2-digit', minute: '2-digit' });
  } catch { return ''; }
};

/**
 * Logic to generate or update player responses for an event
 */
export const processEventResponses = (event, existingResponses, settings, currentHome) => {
  let responses = (existingResponses && !Array.isArray(existingResponses)) ? { ...existingResponses } : {};
  
  if (settings.autoDabei && !event.status?.includes('archived')) {
    const currentHomeNames = new Set(currentHome.map(p => p.name?.trim()).filter(Boolean));
    
    // Remove old auto-generated responses for unlinked/inactive players
    Object.keys(responses).forEach(name => {
      if (responses[name]?.isAutoGenerated && !currentHomeNames.has(name)) {
        delete responses[name];
      }
    });

    // Add missing ones
    currentHome.forEach(p => {
      const playerName = p.name?.trim();
      if (playerName && playerName !== "" && !responses[playerName]) {
        responses[playerName] = { 
          status: 'going', 
          reason: '', 
          timestamp: new Date().toISOString(),
          isAutoGenerated: true 
        };
      }
    });
  }

  return responses;
};
