import { useState, useRef, useCallback } from 'react';
import useStore from '../../store/useStore';
import { formatCalendarDate } from '../../utils/calendarUtils';
import { calculateMeetingTime } from '../../utils/settingsUtils';

export const useCalendarSync = (events, settings, homeSquad, allMembers) => {
  const [isSyncing, setIsSyncing] = useState(false);
  const isSyncingRef = useRef(false);
  const { setCalendarEvents } = useStore();

  const syncFromHnet = useCallback(async (offset = 60) => {
    const freshState = useStore.getState();
    const freshSquad = freshState.squad || {};
    const freshSettings = freshSquad.settings || {};
    const freshHomeSquad = (Array.isArray(freshSquad.home) ? freshSquad.home : []).filter(p => !p.isInactive);
    const freshEvents = Array.isArray(freshSquad.calendarEvents) ? freshSquad.calendarEvents : [];
    const freshHiddenIds = freshSquad.hiddenEventIds || [];

    let teamId = freshSettings?.teamId;
    if ((!teamId || teamId.length > 15) && freshSettings.hnetUrl) {
      const match = freshSettings.hnetUrl.match(/mannschaften\/([^/]+)/);
      if (match && match[1]) teamId = match[1];
    }

    if (!teamId || isSyncingRef.current) return;

    isSyncingRef.current = true;
    setIsSyncing(true);
    try {
      const { syncToCalendar } = await import('../../services/handballNetService');
      const hnetEvents = await syncToCalendar(teamId, freshSettings.homeName || "Wir");
      const merged = [...freshEvents];
      
      hnetEvents.forEach(hEvent => {
        const hnetId = String(hEvent.hnetGameId || "");
        const idx = merged.findIndex(e => String(e.hnetGameId || "") === hnetId);
        const isHidden = freshHiddenIds.includes(hnetId);
        const isArchived = hEvent.status === 'archived';

        if (idx > -1) {
          const existing = merged[idx];
          let responses = (existing.responses && !Array.isArray(existing.responses)) ? { ...existing.responses } : {};
          
          freshHomeSquad.forEach(p => { 
            const playerName = p.name?.trim();
            if (!playerName || responses[playerName]) return;

            const isLinked = (freshState.allMembers || []).some(m => 
              (m.playerName?.trim().toLowerCase() === playerName.toLowerCase()) || (m.playerId === p.id)
            );
            if (!isLinked && !p.isInactive) return;

            if (p.isInactive) {
              responses[playerName] = { status: 'declined', reason: 'Spieler ist inaktiv', timestamp: new Date().toISOString(), isAutoGenerated: true };
            } else if (freshSettings.autoDabei && !isArchived) {
              responses[playerName] = { status: 'going', reason: '', timestamp: new Date().toISOString(), isAutoGenerated: true };
            }
          });

          merged[idx] = {
            ...existing,
            ...hEvent,
            date: formatCalendarDate(hEvent.date, hEvent.time),
            meetingTime: existing.meetingTime || calculateMeetingTime(hEvent.time, offset),
            responses,
            isMandatory: existing.isMandatory ?? freshSettings.absageGrundPflicht,
            isAutoGoing: existing.isAutoGoing ?? freshSettings.autoDabei,
            deadline: existing.deadline ?? freshSettings.absageDeadline
          };
        } else if (!isHidden) {
          const initialResponses = {};
          freshHomeSquad.forEach(p => { 
            const playerName = p.name?.trim();
            if (!playerName) return;
            const isLinked = (freshState.allMembers || []).some(m => 
              (m.playerName?.trim().toLowerCase() === playerName.toLowerCase()) || (m.playerId === p.id)
            );
            if (!isLinked && !p.isInactive) return;

            if (p.isInactive) {
              initialResponses[playerName] = { status: 'declined', reason: 'Spieler ist inaktiv', timestamp: new Date().toISOString(), isAutoGenerated: true };
            } else if (freshSettings.autoDabei && !isArchived) {
              initialResponses[playerName] = { status: 'going', reason: '', timestamp: new Date().toISOString(), isAutoGenerated: true };
            }
          });
          merged.push({
            ...hEvent,
            date: formatCalendarDate(hEvent.date, hEvent.time),
            meetingTime: calculateMeetingTime(hEvent.time, offset),
            responses: initialResponses,
            isMandatory: freshSettings.absageGrundPflicht,
            isAutoGoing: freshSettings.autoDabei,
            deadline: freshSettings.absageDeadline
          });
        }
      });
      
      setCalendarEvents(merged);
      const activeTeamId = useStore.getState().activeTeamId;
      if (activeTeamId) {
        const { default: syncService } = await import('../../services/SyncService');
        syncService.saveBulkEvents(activeTeamId, merged);
      }
    } catch (e) { console.error("Hnet Sync Error:", e); }
    finally {
      isSyncingRef.current = false;
      setIsSyncing(false);
    }
  }, [setCalendarEvents]);

  return { isSyncing, syncFromHnet };
};
