import React, { useState, useEffect } from 'react';
import { 
  Save, Shield, Sword, Target, Users,
  RefreshCw, Calendar, RotateCcw, Info, Check, XCircle
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

// Store
import useStore from '../../store/useStore';

// UI Components
import Button from '../ui/Button';
import SettingsSection from './parts/SettingsSection';
import AnalysisModeSection from './parts/AnalysisModeSection';
import { TeamConfig, PlayerProfile } from './parts/IdentitySection';
import SyncSection from './parts/SyncSection';
import HiddenEventsList from './parts/HiddenEventsList';
import DataManagementSection from './parts/DataManagementSection';

const SettingsManager = () => {
  // --- STORE ---
  const { squad, updateSettings, setCalendarEvents, resetAll, activeTeamId, restoreEvent } = useStore();
  const { settings = {}, home = [], away = [], hiddenEventIds = [] } = squad || {};

  const [hasChanges, setHasChanges] = useState(false);
  const [notification, setNotification] = useState(null);
  const [showResetConfirm, setShowResetConfirm] = useState(false);
  const [isSyncing, setIsSyncing] = useState(false);

  const notify = (msg, type = 'success') => {
    setNotification({ msg, type });
    setTimeout(() => setNotification(null), 3000);
  };

  const handleUpdate = (key, value) => {
    updateSettings({ [key]: value });
    setHasChanges(true);
  };

  const handleSave = () => {
    setHasChanges(false);
    notify('Einstellungen erfolgreich gespeichert');
  };

  const handleApplyToAll = () => {
    const getMeetingTime = (timeStr, offset) => {
      if (!timeStr || !offset) return '';
      try {
        const [h, m] = timeStr.replace(' Uhr', '').split(':').map(Number);
        const d = new Date();
        d.setHours(h, m, 0, 0);
        d.setMinutes(d.getMinutes() - offset);
        return d.toLocaleTimeString('de-DE', { hour: '2-digit', minute: '2-digit' });
      } catch { return ''; }
    };

    const currentHome = (squad?.home || []).filter(p => !p.isInactive);
    const updatedEvents = (squad.calendarEvents || []).map(event => ({
      ...event,
      isMandatory: settings.absageGrundPflicht,
      isAutoGoing: settings.autoDabei,
      deadline: settings.absageDeadline,
      meetingTime: getMeetingTime(event.time, settings.defaultMeetingOffset),
      responses: settings.autoDabei ? {
        ...(event.responses || {}),
        ...currentHome.reduce((acc, p) => {
          const name = p.name?.trim();
          if (name && (!event.responses || !event.responses[name])) {
            acc[name] = { status: 'going', reason: '', timestamp: new Date().toISOString(), isAutoGenerated: true };
          }
          return acc;
        }, {})
      } : (event.responses || {})
    }));
    
    setCalendarEvents(updatedEvents);
    notify('Einstellungen auf alle Spiele angewendet!');
  };

  const handleSync = async () => {
    if (!settings.teamId) return notify('Bitte zuerst Handball.net Link einfügen', 'error');
    setIsSyncing(true);
    
    try {
      const getMeetingTime = (timeStr, offset) => {
        if (!timeStr || !offset) return '';
        try {
          const [h, m] = timeStr.replace(' Uhr', '').split(':').map(Number);
          const d = new Date();
          d.setHours(h, m, 0, 0);
          d.setMinutes(d.getMinutes() - offset);
          return d.toLocaleTimeString('de-DE', { hour: '2-digit', minute: '2-digit' });
        } catch { return ''; }
      };

      const { syncToCalendar } = await import('../../services/handballNetService');
      const hnetEvents = await syncToCalendar(settings.teamId, settings.homeName);
      
      const existingEvents = squad.calendarEvents || [];

      const newCalendarEvents = hnetEvents.map(hEvent => {
        const existing = existingEvents.find(e => e.hnetGameId === hEvent.hnetGameId);
        let responses = (existing?.responses && !Array.isArray(existing.responses)) ? { ...existing.responses } : {};
        
        // Auto-attendance logic: Fill in missing responses for all ACTIVE roster players
        if (settings.autoDabei && !hEvent.status?.includes('archived')) {
          const currentHome = (squad?.home || []).filter(p => !p.isInactive);
          currentHome.forEach(p => {
            const playerName = p.name?.trim();
            if (playerName && playerName !== "" && (!responses || !responses[playerName])) {
              responses[playerName] = { 
                status: 'going', 
                reason: '', 
                timestamp: new Date().toISOString(),
                isAutoGenerated: true 
              };
            }
          });
        }

        return { 
          ...hEvent, 
          responses,
          meetingTime: existing?.meetingTime || getMeetingTime(hEvent.time, settings.defaultMeetingOffset),
          isMandatory: existing?.isMandatory !== undefined ? existing.isMandatory : settings.absageGrundPflicht,
          isAutoGoing: existing?.isAutoGoing !== undefined ? existing.isAutoGoing : settings.autoDabei,
          deadline: existing?.deadline !== undefined ? existing.deadline : settings.absageDeadline
        };
      });

      const nonHnetEvents = existingEvents.filter(e => !e.hnetGameId);
      setCalendarEvents([...nonHnetEvents, ...newCalendarEvents]);
      
      setHasChanges(false);
      notify('Spielplan erfolgreich synchronisiert!');
    } catch (e) {
      notify('Fehler: ' + e.message, 'error');
    } finally {
      setIsSyncing(false);
    }
  };

  const handleReset = async () => {
    await resetAll();
    window.location.reload();
  };

  const colors = ['#84cc16', '#dc3545', '#2563eb', '#f59e0b', '#7c3aed', '#ec4899', '#3f3f46', '#ffffff'];

  return (
    <div className="max-w-[1000px] mx-auto space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500 pb-20">
      
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-black tracking-tighter uppercase italic text-zinc-100">System-Einstellungen</h2>
          <p className="text-xs font-bold text-zinc-500 uppercase tracking-widest mt-1">Konfiguriere dein Sechsmeter Erlebnis</p>
        </div>
        
        {hasChanges && (
          <Button 
            variant="primary" 
            size="lg" 
            icon={Save} 
            onClick={handleSave}
            className="animate-in fade-in zoom-in-95"
          >
            Änderungen Speichern
          </Button>
        )}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        
        {/* Analysis Mode */}
        <SettingsSection title="Analyse-Modus (Wurferfassung)" icon={Target} iconColor="blue" className="md:col-span-2">
          <AnalysisModeSection 
            isZoneMode={settings.isZoneMode} 
            onUpdate={handleUpdate} 
          />
        </SettingsSection>

        {/* Identity Section */}
        <SettingsSection title="Heim-Team (Identity)" icon={Sword} iconColor="brand">
          <TeamConfig 
            label="Dein Teamname"
            name={settings.homeName}
            color={settings.homeColor}
            colors={colors}
            onUpdateName={(val) => handleUpdate('homeName', val)}
            onUpdateColor={(val) => handleUpdate('homeColor', val)}
          />
        </SettingsSection>

        <SettingsSection title="Gast-Team (Gegner)" icon={Shield} iconColor="zinc">
          <TeamConfig 
            label="Gegner Name"
            name={settings.awayName}
            color={settings.awayColor}
            colors={colors}
            onUpdateName={(val) => handleUpdate('awayName', val)}
            onUpdateColor={(val) => handleUpdate('awayColor', val)}
          />
        </SettingsSection>

        {/* Invite Section */}
        <SettingsSection title="Mitspieler einladen" icon={Users} iconColor="brand" className="md:col-span-2 bg-gradient-to-br from-brand/10 to-transparent">
          <div className="flex flex-col md:flex-row gap-6 items-center">
            <div className="flex-1 space-y-2">
              <h4 className="text-sm font-black text-white uppercase italic">Dein Team-Beitrittslink</h4>
              <p className="text-[10px] font-bold text-zinc-500 uppercase leading-relaxed">
                Kopiere diesen Link und schicke ihn an deine Mitspieler. Sie können dann ihren Namen und ihre Nummer eingeben und treten deinem Team sofort bei.
              </p>
            </div>
            <div className="w-full md:w-auto flex gap-2">
              <div className="relative flex-1 md:w-80">
                <input 
                  readOnly
                  value={`${window.location.origin}/join/${activeTeamId || ''}`}
                  className="w-full bg-black/60 border border-zinc-800 rounded-2xl px-6 py-4 text-xs font-bold text-zinc-400 outline-none focus:border-brand transition-all"
                />
              </div>
              <Button 
                variant="primary" 
                size="lg"
                onClick={() => {
                  navigator.clipboard.writeText(`${window.location.origin}/join/${activeTeamId || ''}`);
                  notify('Einladungslink kopiert!');
                }}
              >
                Kopieren
              </Button>
            </div>
          </div>
        </SettingsSection>

        {/* Sync & Calendar */}
        <SettingsSection title="Handball.net & Kalender" icon={Calendar} iconColor="brand" className="md:col-span-2">
          <SyncSection 
            hnetUrl={settings.hnetUrl}
            onUrlChange={(val) => {
              handleUpdate('hnetUrl', val);
              const match = val.match(/mannschaften\/([^/]+)/);
              if (match && match[1]) handleUpdate('teamId', match[1]);
            }}
            settings={settings}
            onUpdate={handleUpdate}
            onSync={handleSync}
            onApplyToAll={handleApplyToAll}
            isSyncing={isSyncing}
          />
          <HiddenEventsList 
            hiddenIds={hiddenEventIds} 
            onRestore={restoreEvent} 
          />
        </SettingsSection>

        {/* Data Management */}
        <SettingsSection title="Daten-Verwaltung" icon={RotateCcw} iconColor="red" className="md:col-span-2">
          <DataManagementSection 
            showResetConfirm={showResetConfirm}
            onReset={handleReset}
            onConfirmToggle={() => {
              if(!showResetConfirm) {
                setShowResetConfirm(true);
                setTimeout(() => setShowResetConfirm(false), 5000);
              } else {
                handleReset();
              }
            }}
          />
        </SettingsSection>
      </div>

      {/* Footer Info */}
      <div className="p-6 bg-brand/5 border border-brand/20 rounded-3xl flex items-center gap-4 text-brand">
        <Info size={20} />
        <p className="text-[10px] font-bold uppercase tracking-[0.1em] leading-relaxed opacity-80">
          Diese Einstellungen beeinflussen das Erscheinungsbild deines <span className="font-black">Taktikboards</span> und der <span className="font-black">Kader-Verwaltung</span>.
        </p>
      </div>

      {/* Notifications */}
      <AnimatePresence>
        {notification && (
          <motion.div 
            initial={{ y: 50, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            exit={{ y: 50, opacity: 0 }}
            className={`fixed bottom-8 left-1/2 -translate-x-1/2 px-6 py-4 rounded-2xl shadow-2xl z-[100] border backdrop-blur-xl flex items-center gap-3
              ${notification.type === 'error' ? 'bg-red-500/90 border-red-500 text-white' : 'bg-zinc-900/90 border-brand/50 text-brand'}`}
          >
            {notification.type === 'error' ? <XCircle size={18} /> : <Check size={18} />}
            <span className="text-[10px] font-black uppercase tracking-widest">{notification.msg}</span>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default SettingsManager;
